#locators of registeration page
link_Reg = "xpath://a[contains(text(),'REGISTER')]"
txt_FirstName = "xpath://input[@name='firstName']"
txt_LastName = "xpath://input[@name='lastName']"
txt_Phone = "xpath://input[@name='phone']"
txt_Email = "xpath://input[@id='userName']"
txt_add1 = "xpath://input[@name='address1']"
txt_add2 = "xpath://input[@name='address2']"
txt_City = "xpath://input[@name='city']"
txt_State = "xpath://input[@name='state']"
txt_Postcode = "xpath://input[@name='postalCode']"
drp_Country = "xpath://select[@name='country']"
txt_Username = "xpath://input[@id='email']"
txt_Password = "xpath://input[@name='password']"
txt_ConfirmPassword = "xpath://input[@name='confirmPassword']"
btn_Submit = "xpath://input[@name='register']"